name: release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Run linting and testing
        run: |
          docker run \
            --rm \
            --volume "$(pwd):/home/user/go/src/local" \
            backplane/goenv \
              make test

      # https://github.com/actions/setup-go
      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.17

      # https://github.com/goreleaser/goreleaser-action
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
