name: test
on:
  pull_request:
  push:
    branches:
      - "main"
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      # https://github.com/actions/setup-go
      - name: Set up Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.16
      
      - name: Run linting and testing
        run: |
          #!/bin/sh
          set -eux
          go install honnef.co/go/tools/cmd/staticcheck@latest
          make