name: test
on:
  pull_request:
  push:
    branches:
      - "main"
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0

      - name: Run linting and testing
        run: |
          docker run \
            --rm \
            --volume "$(pwd):/home/user/go/src/local" \
            backplane/goenv \
              make test
